#!/bin/bash

# https://stackoverflow.com/questions/27569555/hide-common-base-class-from-doxygen-class-diagram.

LABELS_TO_FILTER="Q[^<>,\"]* Q[^<>,\"]< *Q[^<>,\"]*> Q[^<>\"]< *Q[^<>,\"]*, *Q[^<>,\"]*>"

ARGS=$@

for ARG in ${ARGS}
do
    if [ -e ${ARG} ]
    then
        FILENAME=$(basename "${ARG}")
        EXT="${FILENAME##*.}"

        if [ ${EXT} == "dot" ]
        then
            DOT_FILE=${ARG}

            for LABEL_TO_FILTER in ${LABELS_TO_FILTER}
            do
                NODE_NAMES=$(grep "label=\"${LABEL_TO_FILTER}\"" ${DOT_FILE} | awk '{print $1}')

                if [[ ! -z "${NODE_NAMES}" ]]
                then
                    for NODE_NAME in ${NODE_NAMES}
                    do
                        echo "${NODE_NAME} is a Qt class, filtering..."
                        sed -i "/${NODE_NAME}/d" ${DOT_FILE}
                    done
                fi
            done

            break
        fi
    fi
done

dot ${ARGS}