title: Imgbrd-Grabber
subtitle: Booru browsing made easy
description: Very customizable imageboard/booru browser and mass downloader, with powerful filenaming features.
logo: assets/img/icon.png
show_download: true
google_analytics: UA-22768717-4
discord_url: https://discord.gg/pWnY5eW3rz
theme:
lang: en_US
relative_permalinks: false
baseurl: /imgbrd-grabber
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"

exclude:
- vendor/
- release/
- releases/
- languages/
- cli/
- gui/
- tests/

kramdown:
  header_offset: 1

collections:
  docs:
    permalink: "/:collection/:path.html"
    output: true
  sources:
    permalink: "/docs/:collection/:path.html"
    output: true
  posts:
    permalink: "/blog/:year/:month/:day/:title.html"
    output: true
  category:
    permalink: "/blog/:collection/:path.html"
    output: true

gems:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

webmaster_verifications:
  google: HUsU9v5lhoPPeKdafhViSRi1NofQwzQrRwLN1nEzsA8

defaults:
  - scope:
      path: ""
    values:
      image: assets/img/icon.png
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _sources
      type: sources
    values:
      layout: sources
  - scope:
      path: _posts
      type: post
    values:
      layout: blog_post
  - scope:
      path: _category
      type: category
    values:
      layout: blog_category
